PonedelkoRazieb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("server.urls")),
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from payment.views import payment_card, progress_payment, get_payment_status


app_name = "payment"


urlpatterns = [
    path("self/", payment_card, name="payment_self"),
    path("someone/", payment_card, name="payment_someone"),
    path("progress_payment/", progress_payment, name="progress_payment"),
    path("status/<uuid:payment_uid>/", get_payment_status, name="get_payment_status")
]

server/urls.py
from django.urls import path

from server.views import Main, AccountView, LogIn, LogOut, SignUp, UpdateProfileInfo, CartView, add_to_cart, \
    delete_from_cart, remove_from_cart, change_cart, OrderView

urlpatterns = [
    path("", Main.as_view(), name="index"),
    path("account/", AccountView.as_view(), name="account"),
    path("accounts/login/", LogIn.as_view(), name="login"),
    path("account/logout/", LogOut.as_view(), name="logout"),
    path("account/register/", SignUp.as_view(), name="sign-up"),
    path("account/profile/", UpdateProfileInfo.as_view(), name="profile"),
    path('cart/', CartView.as_view(), name="cart"),
    path('add_to_cart/', add_to_cart, name="add_to_cart"),
    path('delete_from_cart/', delete_from_cart, name="delete_from_cart"),
    path('remove_from_cart/', remove_from_cart, name="remove_from_cart"),
    path('change_cart/', change_cart, name="change_cart"),
    path('order/', OrderView.as_view(), name="order")
]

payment/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.decorators.http import require_POST, require_GET

from payment.services import PaymentProcessing


@login_required
@require_GET
def payment_card(request):
    """
    Представление оплаты заказа
    """
    form_filename = "payment_someone_form" if "someone" in request.path else "payment_self_form"
    context = {
        'payment_form': f'payment/includes/{form_filename}.html',
        'breadcrumb_title': "Оплата заказа"
    }
    return render(request, "payment/payment.html", context)


@login_required
@require_POST
def progress_payment(request):
    """
    Отправка данных на оплату
    """
    numer = request.POST.get('numero1')
    status = PaymentProcessing(card_number=numer)
    status.processing()
    payment_uid = status.payment_uid
    return render(request, "payment/partials/progressPayment.html", {"payment_uid": payment_uid})


@login_required
@require_GET
def get_payment_status(request, payment_uid):
    """
    Получение статуса оплаты
    """
    status = PaymentProcessing()
    result = status.get_status(payment_uid)
    return render(request, "payment/partials/payment_status.html", {"result": result})

templates/payment/partials/payment_status.html
<div class="ProgressPayment">
    <div class="ProgressPayment-title">{{ result.status }}
    </div>
    <div class="ProgressPayment-title">{{ result.error_message }}
    </div>
</div>

templates/payment/partials/progressPayment.html
<div class="ProgressPayment"
     hx-get="{% url 'payment:get_payment_status' payment_uid=payment_uid %}"
     hx-trigger="load delay:4s"
     hx-swap="outerHTML">

    <div class="ProgressPayment-title">Ждем подтверждения оплаты платежной системой
    </div>
    <div class="ProgressPayment-title">Идентификатор оплаты: {{ id }}
    </div>
    <div class="ProgressPayment-icon">
        <div class="cssload-thecube">
            <div class="cssload-cube cssload-c1"></div>
            <div class="cssload-cube cssload-c2"></div>
            <div class="cssload-cube cssload-c4"></div>
            <div class="cssload-cube cssload-c3"></div>
        </div>
    </div>
</div>